/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    About: typeof import('./../components/about.vue')['default']
    Resume: typeof import('./../components/resume.vue')['default']
    TemplateAll: typeof import('./../components/template/all.vue')['default']
    TemplateList: typeof import('./../components/template/list.vue')['default']
  }
}
